#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
timestamp="$(date +%Y%m%d%H%M%S)"
dry_run=0

usage() {
  cat <<'USAGE'
Usage: install.sh [--dry-run]

Installs or refreshes portable AI-agent configuration symlinks for this clone.
Existing managed targets are backed up before replacement.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      dry_run=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

link_path() {
  local source_path="$1"
  local target_path="$2"
  local parent_path
  parent_path="$(dirname "$target_path")"

  if [ "$dry_run" -eq 0 ]; then
    mkdir -p "$parent_path"
  elif [ ! -d "$parent_path" ]; then
    printf 'would create directory: %s\n' "$parent_path"
  fi

  if [ -L "$target_path" ]; then
    local current_target
    current_target="$(readlink "$target_path")"
    if [ "$current_target" = "$source_path" ]; then
      printf 'already linked: %s -> %s\n' "$target_path" "$source_path"
      return 0
    fi
    if [ "$dry_run" -eq 1 ]; then
      printf 'would replace symlink: %s -> %s\n' "$target_path" "$source_path"
      return 0
    fi
    unlink "$target_path"
  elif [ -e "$target_path" ]; then
    local backup_path="${target_path}.backup-${timestamp}"
    if [ "$dry_run" -eq 1 ]; then
      printf 'would back up: %s -> %s\n' "$target_path" "$backup_path"
      printf 'would link: %s -> %s\n' "$target_path" "$source_path"
      return 0
    fi
    mv "$target_path" "$backup_path"
    printf 'backed up: %s -> %s\n' "$target_path" "$backup_path"
  fi

  if [ "$dry_run" -eq 1 ]; then
    printf 'would link: %s -> %s\n' "$target_path" "$source_path"
    return 0
  fi

  ln -s "$source_path" "$target_path"
  printf 'linked: %s -> %s\n' "$target_path" "$source_path"
}

json_escape() {
  local raw_value="$1"
  raw_value="${raw_value//\\/\\\\}"
  raw_value="${raw_value//\"/\\\"}"
  printf '%s' "$raw_value"
}

print_opencode_config() {
  local instructions_path
  local skills_path
  local global_skills_path
  instructions_path="$(json_escape "$repo_root/instructions/AGENTS.md")"
  skills_path="$(json_escape "$repo_root/skills")"
  global_skills_path="$(json_escape "$HOME/.config/opencode/skills")"

  printf '%s\n' '{'
  printf '%s\n' '  // Generated by ai-agent-setup/scripts/install.sh. Do not commit this machine-local file.'
  printf '%s\n' '  "$schema": "https://opencode.ai/config.json",'
  printf '  "instructions": ["%s"],\n' "$instructions_path"
  printf '%s\n' '  "skills": {'
  printf '    "paths": ["%s", "%s"]\n' "$skills_path" "$global_skills_path"
  printf '%s\n' '  },'
  printf '%s\n' '  "permission": {'
  printf '%s\n' '    "edit": "ask",'
  printf '%s\n' '    "bash": {'
  printf '%s\n' '      "*": "ask",'
  printf '%s\n' '      "git push*": "deny",'
  printf '%s\n' '      "git reset --hard*": "deny",'
  printf '%s\n' '      "rm -rf*": "deny"'
  printf '%s\n' '    },'
  printf '%s\n' '    "webfetch": "ask"'
  printf '%s\n' '  }'
  printf '%s\n' '}'
}

write_opencode_config() {
  local target_path="$HOME/.config/opencode/opencode.jsonc"
  local parent_path
  parent_path="$(dirname "$target_path")"

  if [ "$dry_run" -eq 0 ]; then
    mkdir -p "$parent_path"
  elif [ ! -d "$parent_path" ]; then
    printf 'would create directory: %s\n' "$parent_path"
  fi

  if [ -L "$target_path" ]; then
    local backup_path="${target_path}.backup-${timestamp}"
    if [ "$dry_run" -eq 1 ]; then
      printf 'would back up symlink: %s -> %s\n' "$target_path" "$backup_path"
      printf 'would configure: %s\n' "$target_path"
      return 0
    fi
    mv "$target_path" "$backup_path"
    printf 'backed up symlink: %s -> %s\n' "$target_path" "$backup_path"
  elif [ -e "$target_path" ]; then
    if cmp -s "$target_path" <(print_opencode_config); then
      printf 'already configured: %s\n' "$target_path"
      return 0
    fi
    local backup_path="${target_path}.backup-${timestamp}"
    if [ "$dry_run" -eq 1 ]; then
      printf 'would back up: %s -> %s\n' "$target_path" "$backup_path"
      printf 'would configure: %s\n' "$target_path"
      return 0
    fi
    mv "$target_path" "$backup_path"
    printf 'backed up: %s -> %s\n' "$target_path" "$backup_path"
  fi

  if [ "$dry_run" -eq 1 ]; then
    printf 'would configure: %s\n' "$target_path"
    return 0
  fi

  print_opencode_config >"$target_path"
  printf 'configured: %s\n' "$target_path"
}

merge_skills_from_agents() {
  local agents_skills="$repo_root/.agents/skills"
  local project_skills="$repo_root/skills"

  if [ ! -d "$agents_skills" ]; then
    return 0
  fi

  local merged=0
  for skill_dir in "$agents_skills"/*/; do
    [ -d "$skill_dir" ] || continue
    local skill_name
    skill_name="$(basename "$skill_dir")"

    if [ -d "$project_skills/$skill_name" ]; then
      if [ "$dry_run" -eq 1 ]; then
        printf 'skill already exists in skills/: %s (skipping)\n' "$skill_name"
      fi
      continue
    fi

    if [ "$dry_run" -eq 1 ]; then
      printf 'would merge: .agents/skills/%s -> skills/%s\n' "$skill_name" "$skill_name"
      merged=$((merged + 1))
      continue
    fi

    mv "$skill_dir" "$project_skills/$skill_name"
    printf 'merged: .agents/skills/%s -> skills/%s\n' "$skill_name" "$skill_name"
    merged=$((merged + 1))
  done

  if [ "$merged" -gt 0 ] && [ "$dry_run" -eq 0 ]; then
    # Remove broken symlinks in .claude/skills/ that point into .agents/skills/
    if [ -d "$repo_root/.claude/skills" ]; then
      for link in "$repo_root/.claude/skills"/*; do
        [ -L "$link" ] || continue
        local link_target
        link_target="$(readlink "$link" 2>/dev/null || true)"
        case "$link_target" in
          *../../.agents/skills/*)
            unlink "$link"
            printf 'removed broken symlink: .claude/skills/%s\n' "$(basename "$link")"
            ;;
        esac
      done
      # Remove .claude/skills/ if empty (the global symlink covers this)
      if [ -z "$(ls -A "$repo_root/.claude/skills" 2>/dev/null)" ]; then
        rmdir "$repo_root/.claude/skills"
      fi
    fi

    # Clean up empty .agents/skills/ and .agents/
    if [ -d "$agents_skills" ] && [ -z "$(ls -A "$agents_skills" 2>/dev/null)" ]; then
      rmdir "$agents_skills"
      if [ -d "$repo_root/.agents" ] && [ -z "$(ls -A "$repo_root/.agents" 2>/dev/null)" ]; then
        rmdir "$repo_root/.agents"
      fi
    fi
  fi
}

merge_skills_from_agents

link_path "$repo_root/skills" "$HOME/.agents/skills"

link_path "$repo_root/instructions/AGENTS.md" "$HOME/.claude/AGENTS.md"
link_path "$repo_root/instructions/CLAUDE.md" "$HOME/.claude/CLAUDE.md"
link_path "$repo_root/skills" "$HOME/.claude/skills"
link_path "$repo_root/agents/claude" "$HOME/.claude/agents"
link_path "$repo_root/commands/claude" "$HOME/.claude/commands"

write_opencode_config
link_path "$repo_root/agents/opencode" "$HOME/.config/opencode/agent"
link_path "$repo_root/commands/opencode" "$HOME/.config/opencode/command"

link_path "$repo_root/skills" "$HOME/.copilot/skills"
link_path "$repo_root/agents/copilot" "$HOME/.copilot/agents"
link_path "$repo_root/adapters/copilot/instructions" "$HOME/.copilot/.github/instructions"
link_path "$repo_root/commands/copilot-prompts" "$HOME/.copilot/.github/prompts"

printf '\nRestart opencode after config changes; it does not hot-reload config.\n'
