#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

unlink_if_repo_link() {
  local target_path="$1"

  if [ ! -L "$target_path" ]; then
    printf 'not a symlink: %s\n' "$target_path"
    return 0
  fi

  local current_target
  current_target="$(readlink "$target_path")"
  case "$current_target" in
    "$repo_root"*)
      unlink "$target_path"
      printf 'unlinked: %s\n' "$target_path"
      ;;
    *)
      printf 'skipped non-repo symlink: %s -> %s\n' "$target_path" "$current_target"
      ;;
  esac
}

unlink_generated_opencode_config() {
  local target_path="$HOME/.config/opencode/opencode.jsonc"

  if [ -L "$target_path" ]; then
    unlink_if_repo_link "$target_path"
    return 0
  fi

  if [ ! -f "$target_path" ]; then
    printf 'not a generated file: %s\n' "$target_path"
    return 0
  fi

  if grep -Fq 'Generated by ai-agent-setup/scripts/install.sh' "$target_path" || grep -Fq 'Generated by ai-agent-setup/scripts/link.sh' "$target_path"; then
    rm "$target_path"
    printf 'removed generated file: %s\n' "$target_path"
  else
    printf 'skipped non-generated file: %s\n' "$target_path"
  fi
}

unlink_if_repo_link "$HOME/.agents/skills"

unlink_if_repo_link "$HOME/.claude/AGENTS.md"
unlink_if_repo_link "$HOME/.claude/CLAUDE.md"
unlink_if_repo_link "$HOME/.claude/skills"
unlink_if_repo_link "$HOME/.claude/agents"
unlink_if_repo_link "$HOME/.claude/commands"

unlink_generated_opencode_config
unlink_if_repo_link "$HOME/.config/opencode/agent"
unlink_if_repo_link "$HOME/.config/opencode/command"

unlink_if_repo_link "$HOME/.copilot/skills"
unlink_if_repo_link "$HOME/.copilot/agents"
unlink_if_repo_link "$HOME/.copilot/.github/instructions"
unlink_if_repo_link "$HOME/.copilot/.github/prompts"

unlink_if_repo_link "$HOME/.gemini/config/AGENTS.md"
unlink_if_repo_link "$HOME/.gemini/config/skills"
unlink_if_repo_link "$HOME/.gemini/config/agents"

printf '\nBackups are not restored automatically. Restore the matching *.backup-* path manually if needed.\n'
