#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
failed=0
warnings=0
check_claude=0
check_opencode=0
check_copilot=0

usage() {
  cat <<'USAGE'
Usage: verify.sh [--harness claude|opencode|copilot]... [--all]

Validates the portable AI-agent setup for this clone.
When no harness is specified, all supported harnesses are checked.
USAGE
}

select_all_harnesses() {
  check_claude=1
  check_opencode=1
  check_copilot=1
}

if [ "$#" -eq 0 ]; then
  select_all_harnesses
fi

while [ "$#" -gt 0 ]; do
  case "$1" in
    --harness)
      case "${2:-}" in
        claude) check_claude=1 ;;
        opencode) check_opencode=1 ;;
        copilot) check_copilot=1 ;;
        *) printf 'Unknown harness: %s\n' "${2:-}" >&2; usage >&2; exit 2 ;;
      esac
      shift 2
      ;;
    --all)
      select_all_harnesses
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

check_command() {
  local command_name="$1"
  if command -v "$command_name" >/dev/null 2>&1; then
    printf 'ok: command available: %s (%s)\n' "$command_name" "$(command -v "$command_name")"
  else
    printf 'missing: command not found: %s\n' "$command_name"
    failed=1
  fi
}

check_link() {
  local target_path="$1"
  local expected_path="$2"

  if [ ! -L "$target_path" ]; then
    printf 'missing link: %s\n' "$target_path"
    failed=1
    return 0
  fi

  local current_target
  current_target="$(readlink "$target_path")"
  if [ "$current_target" = "$expected_path" ]; then
    printf 'ok: %s -> %s\n' "$target_path" "$expected_path"
  else
    printf 'wrong link: %s -> %s (expected %s)\n' "$target_path" "$current_target" "$expected_path"
    failed=1
  fi
}

check_file_contains() {
  local target_path="$1"
  local expected_text="$2"
  local label="$3"

  if [ ! -f "$target_path" ]; then
    printf 'missing file: %s\n' "$target_path"
    failed=1
    return 0
  fi

  if grep -Fq "$expected_text" "$target_path"; then
    printf 'ok: %s: %s\n' "$label" "$target_path"
  else
    printf 'missing expected content: %s (%s)\n' "$target_path" "$label"
    failed=1
  fi
}

check_required_path() {
  local path_to_check="$1"
  if [ -e "$path_to_check" ]; then
    printf 'ok: exists: %s\n' "$path_to_check"
  else
    printf 'missing: %s\n' "$path_to_check"
    failed=1
  fi
}

printf 'Checking local commands only. No model/provider calls are made.\n\n'

[ "$check_claude" -eq 1 ] && check_command claude
[ "$check_opencode" -eq 1 ] && check_command opencode
[ "$check_copilot" -eq 1 ] && check_command copilot

printf '\nChecking required repository paths.\n'
check_required_path "$repo_root/instructions/AGENTS.md"
check_required_path "$repo_root/instructions/stacks/python-fastapi-ddd.md"
check_required_path "$repo_root/skills/tdd/SKILL.md"
check_required_path "$repo_root/skills/find-skills/SKILL.md"
check_required_path "$repo_root/skills/python-fastapi-ddd/SKILL.md"
check_required_path "$repo_root/skills/git-repo-flow/SKILL.md"
check_required_path "$repo_root/profiles/model-profiles.jsonc"

if [ "$check_claude" -eq 1 ]; then
  check_required_path "$repo_root/instructions/CLAUDE.md"
  check_required_path "$repo_root/agents/claude/code-review.md"
  check_required_path "$repo_root/agents/claude/tech-lead.md"
  check_required_path "$repo_root/agents/claude/postgresql.md"
  check_required_path "$repo_root/agents/claude/terraform.md"
fi

if [ "$check_opencode" -eq 1 ]; then
  check_required_path "$repo_root/agents/opencode/code-review.md"
  check_required_path "$repo_root/agents/opencode/tech-lead.md"
  check_required_path "$repo_root/agents/opencode/postgresql.md"
  check_required_path "$repo_root/agents/opencode/terraform.md"
  check_required_path "$repo_root/adapters/opencode/opencode.jsonc"
fi

if [ "$check_copilot" -eq 1 ]; then
  check_required_path "$repo_root/agents/copilot/code-review.agent.md"
  check_required_path "$repo_root/agents/copilot/product-ba.agent.md"
  check_required_path "$repo_root/agents/copilot/postgresql.agent.md"
  check_required_path "$repo_root/agents/copilot/terraform.agent.md"
fi

printf '\nChecking symlinks.\n'
check_link "$HOME/.agents/skills" "$repo_root/skills"

if [ "$check_claude" -eq 1 ]; then
  check_link "$HOME/.claude/AGENTS.md" "$repo_root/instructions/AGENTS.md"
  check_link "$HOME/.claude/CLAUDE.md" "$repo_root/instructions/CLAUDE.md"
  check_link "$HOME/.claude/skills" "$repo_root/skills"
  check_link "$HOME/.claude/agents" "$repo_root/agents/claude"
  check_link "$HOME/.claude/commands" "$repo_root/commands/claude"
fi

if [ "$check_opencode" -eq 1 ]; then
  check_file_contains "$HOME/.config/opencode/opencode.jsonc" 'Generated by ai-agent-setup/scripts/install.sh' 'opencode config generated by install.sh'
  check_file_contains "$HOME/.config/opencode/opencode.jsonc" "$repo_root/instructions/AGENTS.md" 'opencode instructions path'
  check_file_contains "$HOME/.config/opencode/opencode.jsonc" "$repo_root/skills" 'opencode skills path'
  check_link "$HOME/.config/opencode/agent" "$repo_root/agents/opencode"
  check_link "$HOME/.config/opencode/command" "$repo_root/commands/opencode"
fi

if [ "$check_copilot" -eq 1 ]; then
  check_link "$HOME/.copilot/skills" "$repo_root/skills"
  check_link "$HOME/.copilot/agents" "$repo_root/agents/copilot"
  check_link "$HOME/.copilot/.github/instructions" "$repo_root/adapters/copilot/instructions"
  check_link "$HOME/.copilot/.github/prompts" "$repo_root/commands/copilot-prompts"
fi

printf '\nChecking git aliases.\n'
for alias_name in sync resync feature; do
  if git config --global --get "alias.${alias_name}" >/dev/null 2>&1; then
    printf 'ok: git alias available: %s\n' "$alias_name"
  else
    printf 'warn: git alias not found: %s\n' "$alias_name"
    warnings=1
  fi
done

if [ "$failed" -eq 0 ]; then
  if [ "$warnings" -eq 0 ]; then
    printf '\nVerification passed.\n'
  else
    printf '\nVerification passed with warnings.\n'
  fi
else
  printf '\nVerification found issues.\n'
fi

exit "$failed"
